var should = require("should");
require.pkg = require("./npm-trospect");
require.scan = require("./scanner");

describe('npm-scope', function(){
    
    it('is running with the expected packages for testing', function(){
        require('prime');
    });
    
    it('can pull the package information for prime', function(done){
        require.scan.full(require.pkg('prime'), function(data){
            data.scanned_subpackages.should.include('prime/collection/hash');
            data.scanned_subpackages.should.include('prime/collection/list');
            data.scanned_subpackages.should.include('prime/collection/map');
            data.scanned_subpackages.should.include('prime/es5/array');
            data.scanned_subpackages.should.include('prime/es5/function');
            data.scanned_subpackages.should.include('prime/es5/number');
            data.scanned_subpackages.should.include('prime/es5/regexp');
            data.scanned_subpackages.should.include('prime/es5/string');
            data.scanned_subpackages.should.include('prime/types/number');
            data.scanned_subpackages.should.include('prime/types/string');
            data.scanned_subpackages.should.include('prime/util/emitter');
            data.scanned_subpackages.should.include('prime/util/ghost');
            data.scanned_subpackages.should.include('prime/util/shell');
            data.scanned_subpackages.should.include('prime/util/type');
            var arrayPackage = require.pkg('prime/es5/array');
            arrayPackage.main.should.equal('es5/array.js');
            arrayPackage.autogenerated.should.equal(true);
            arrayPackage.name.should.equal('prime');
            done();
        });
    });
    
    it('can pull the package information for should', function(done){
        require.scan.full('should', function(data){
            data.merged_dependencies.util.should.equal('*');
            data.merged_dependencies.http.should.equal('*');
            data.merged_dependencies.assert.should.equal('*');
            data.merged_dependencies['should/lib/eql'].should.equal('*');
            data.scanned_subpackages.should.include('should/index');
            data.scanned_subpackages.should.include('should/lib/eql');
            done();
        });
    });
});